name: todo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Drift
  drift: ^2.5.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0
  # RiverPod
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.2.0
  flutter_riverpod: ^2.2.0
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.5.2
  build_runner: ^2.3.3
  freezed: ^2.3.2

flutter:
  uses-material-design: true

